---
deployment:
  tasks:
    - export DEPLOYPATH=/home/dextzgsl/indiecomic.ninja/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R posts $DEPLOYPATH
